### ISSUE TITLE
redmine 2.5.2 compatible?

### ISSUE THREAD

**Issue by jurgenweber** [sukima/redmine_equipment_status_viewer#67]
using the plugin with master.

https://redmine.example.com/equipment_assets:
```
Page not found

The page you were trying to access doesn't exist or has been removed.
```
and in the logs
```
ActionController::RoutingError (uninitialized constant EquipmentAssetsController):
  activesupport (3.2.19) lib/active_support/inflector/methods.rb:230:in `block in constantize'
  activesupport (3.2.19) lib/active_support/inflector/methods.rb:229:in `each'
  activesupport (3.2.19) lib/active_support/inflector/methods.rb:229:in `constantize'
  actionpack (3.2.19) lib/action_dispatch/routing/route_set.rb:69:in `controller_reference'
  actionpack (3.2.19) lib/action_dispatch/routing/route_set.rb:54:in `controller'
  actionpack (3.2.19) lib/action_dispatch/routing/route_set.rb:32:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in `block in call'
  journey (1.0.4) lib/journey/router.rb:56:in `each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.19) lib/action_dispatch/routing/route_set.rb:608:in `call'
  rack-openid (1.4.2) lib/rack/openid.rb:98:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.5) lib/rack/etag.rb:23:in `call'
  rack (1.4.5) lib/rack/conditionalget.rb:25:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.5) lib/rack/session/abstract/id.rb:210:in `context'
  rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/cookies.rb:341:in `call'
  activerecord (3.2.19) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.19) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.19) lib/active_support/callbacks.rb:405:in `_run__2862202752837351898__call__3665599781395625621__callbacks'
  activesupport (3.2.19) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.19) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.19) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.19) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.19) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.19) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.19) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.19) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.19) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/static.rb:63:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in `lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.19) lib/rails/engine.rb:484:in `call'
  railties (3.2.19) lib/rails/application.rb:231:in `call'
  railties (3.2.19) lib/rails/railtie/configurable.rb:30:in `method_missing'
  puma (2.9.1) lib/puma/configuration.rb:71:in `call'
  puma (2.9.1) lib/puma/server.rb:490:in `handle_request'
  puma (2.9.1) lib/puma/server.rb:361:in `process_client'
  puma (2.9.1) lib/puma/server.rb:254:in `block in run'
  puma (2.9.1) lib/puma/thread_pool.rb:92:in `call'
  puma (2.9.1) lib/puma/thread_pool.rb:92:in `block in spawn_thread'
```
alternatively:
https://redmine.foodpanda.berlin/settings/plugin/redmine_equipment_status_viewer
```
404

The page you were trying to access doesn't exist or has been removed.
```

nothing in the logs beyond:
```
Started GET "/settings/plugin/redmine_equipment_status_viewer" for 127.0.0.1 at 2014-10-23 10:10:42 +0000
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"redmine_equipment_status_viewer"}
  Current user: admin (id=1)
  Rendered settings/plugin.html.erb within layouts/admin (1.7ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.1ms)
Completed 404 Not Found in 47.9ms (Views: 4.7ms | ActiveRecord: 0.3ms)
Started GET "/equipment_assets" for 127.0.0.1 at 2014-10-23 10:10:45 +0000
```

any ideas? migrations have been run.

**Comment by fastuser** [comment]
Great feature and would be great to have it updated to latest Redmine versions.
Does anyone want to get paid to do this? Do you want to quote on it ?

**Comment by mrPsycho** [comment]
it works on "Redmine 2.5.2.stable" fine

redmine runs with unicorn under rvm.

**Comment by jurgenweber** [comment]
since when? Did someone update it? I was getting the above error how did you resolve it?

**Comment by sukima** [comment]
I haven't touched it. I closed when I saw @mrPsycho say it worked. But if it doesn't work I can't maintain it any longer and so the following disclaimer is in effect:

>  I can no longer maintain this code on my own. I need contributions to make any effort worth while. I no longer use this in my day to day work and have no intention to provide support all on my own. This project follows a very loose contribution process in that a simple pull request is all that is needed to be given commit access. If you want a feature or have it upgraded to the latest version of Redmine or Rails I ask that you make a Pull Request with that change so that others can also benefit.
>
> Redmine Equipment Status Viewer is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by jurgenweber** [comment]
sure but it's an issue ticket and this is a community project.. so if it works then he should explain how he resolved the issue.. or how he installed it to make it work.

**Comment by mrPsycho** [comment]
@jurgenweber i can't say any special things that i've done. 

maybe it works in 2.5.2 cause i installed it far ago and just upgraded to 2.5.2. 
on this weekend i'll update redmine to 3.0.3 and i can check work ability. 


all installation was made by [redmine manual](http://www.redmine.org/projects/redmine/wiki/Plugins)
